version: '3.4'

services:
  command:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DemoMode__Enabled=false
      - APP_ENV=docker
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  query:
    environment:
      - CORS__AllowedOrigins=https://localhost:10000
      - APP_ENV=docker
  commandstatus:
    environment:
      - CORS__AllowedOrigins=https://localhost:10000
      - APP_ENV=docker

networks:
  default:
    external:
      name: auctionhouse
