version: '3.4'

services:
  command:
    environment:
      - ConnectionStrings__AppConfigurationProd
      - AzureCredentials__AZURE_CLIENT_SECRET
      - AzureCredentials__AZURE_CLIENT_ID
      - AzureCredentials__AZURE_TENANT_ID
      - APP_ENV
  query:
    environment:
      - CORS__AllowedOrigins=https://pekalam.online
      - ConnectionStrings__AppConfigurationProd
      - AzureCredentials__AZURE_CLIENT_SECRET
      - AzureCredentials__AZURE_CLIENT_ID
      - AzureCredentials__AZURE_TENANT_ID
      - APP_ENV
  commandstatus:
    environment:
      - CORS__AllowedOrigins=https://pekalam.online
