trigger:
- sqlserver

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2.401'
  inputs:
    packageType: sdk
    version: 2.2.401
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: ShellScript@2
  displayName: 'Domain tests'
  inputs:
    scriptPath: 'backend/cli/local-run_domain_tests.sh'
    cwd: 'backend/cli'
- task: ShellScript@2
  displayName: 'Unit tests'
  inputs:
    scriptPath: 'backend/cli/local-run_unit_tests.sh'
    cwd: 'backend/cli'
- task: ShellScript@2
  displayName: 'Integration tests'
  inputs:
    scriptPath: 'backend/cli/docker-run_integration_tests.sh'
    cwd: 'backend/cli'
- task: ShellScript@2
  displayName: 'Functional tests'
  inputs:
    scriptPath: 'backend/cli/docker-run_functional_tests.sh'
    cwd: 'backend/cli'
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    msbuildArchitecture: 'x64'
- task: ShellScript@2
  displayName: 'Command database tests'
  inputs:
    scriptPath: 'backend/cli/docker-run_command_db_tests.sh'
    cwd: 'backend/cli'
