trigger:
- sqlserver

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.401'
- task: UseNode@1
  inputs:
    version: '12.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'backend\src\**\*.csproj'
    feedsToUse: 'select'
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: 'backend\src\*.sln'
    vsVersion: '16.0'
    msbuildArchitecture: 'x64'