trigger:
- master

pool: myserver

stages:
- stage: Build
  jobs:
  - job: 'build_local'
    displayName: 'Build project with .net cli'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk from global.json'
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
        workingDirectory: 'backend/src'
    - task: DotNetCoreCLI@2
      displayName: 'Build WebAPI'
      inputs:
        command: 'build'
        arguments: 'Auctionhouse.WebAPI.slnf'
        workingDirectory: 'backend/src'
  - job: 'build_docker'
    displayName: 'Build project with docker and publish'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Run domain tests'
      inputs:
        command: 'test'
        projects: '**/Test.*Domain'
        testRunTitle: 'Domain tests'
        workingDirectory: 'backend/src'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'VPSDockerRegistry'
        dockerComposeFile: 'backend/src/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'build'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'VPSDockerRegistry'
        dockerComposeFile: 'backend/src/docker-compose.yml'
        action: 'Push services'
- stage: Deployment
  jobs:
  - deployment: 'VPSDeployment'   # name of the deployment job, A-Z, a-z, 0-9, and underscore. The word "deploy" is a keyword and is unsupported as the deployment name.
    displayName: 'VPS Deployment' 
    environment: vps-production
    strategy:
      runOnce:    #rolling, canary are the other strategies that are supported
        deploy:
          steps:
            - task: AzureKeyVault@2
              inputs:
                azureSubscription: 'Azure for Students(54a8b190-aefa-4989-849f-3931ec46cb62)'
                KeyVaultName: 'auctionhouse-kv-prod'
                SecretsFilter: '*'
                RunAsPreJob: false
            - task: SSH@0
              inputs:
                sshEndpoint: 'OVH_vps'
                runOptions: 'commands'
                commands: 'echo $(pekalam-me-12) | base64 --decode | docker secret create envoy_ssl_pkcs12 -'
                readyTimeout: '20000'