version: '3.4'

services:
  db-config1:
    hostname: db-config1
    image: mongodb_db-config1
    tmpfs: /data/configdb
    command: "--configsvr --replSet configRS --bind_ip_all"
  db-mongos1:
    hostname: db-mongos1
    image: mongodb_db-mongos1
    command: ["--wait-for", "db-config1:32112", "db-node1:32112" , "db-node2:32112", "--configdb", "configRS/db-config1:27019", "--bind_ip_all"]
    ports: 
      - "27017:27017"
  db-node1:
    hostname: db-node1
    image: mongodb_db-node1
    command: [ "--bind_ip_all", "--replSet", "n1", "--shardsvr" ]
  db-node2:
    hostname: db-node2
    image: mongodb_db-node2
    command: [ "--bind_ip_all", "--replSet", "n2", "--shardsvr" ]
  update-server:
    hostname: update-server
    image: mongodb_update-server
    tty: true
    command: ["--wait-for", "db-mongos1:32112"]
