version: '3.4'

services:
  mongodb:
    container_name: mongodb
    tmpfs: /data/db
    build:
      context: ../src/Test.IntegrationTests
      dockerfile: Dockerfile-mongo-standalone-replicaset
    ports:
      - "27017:27017"

  sql_server:
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Qwerty1234
      - MSSQL_AGENT_ENABLED=True
    ports:
      - '1433:1433'
    image: marekbf3/auctionhouse-sqlserver
    healthcheck:
      test: "sqlcmd -S 127.0.0.1 -U sa -P 'Qwerty1234' -d AuctionhouseDatabase -b -Q 'select distinct 1 from dbo.Events' || exit 1"

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    tmpfs: /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'


  auctionhouse-integration-tests:
    container_name: auctionhouse-integration-tests
    command: > 
      /bin/sh -c "wait-for-services && dotnet test --no-build -s docker.runsettings -v n"
    build:
      context: ../src
      dockerfile: Test.IntegrationTests/Dockerfile
    depends_on:
      - sql_server
      - mongodb
      - rabbitmq


