services:

  envoy1:
    ports:
      - "10000:10000"
    image: envoyproxy/envoy-dev:fe17c1c95e26fbd34266b7a8c1f1acd7d78ba41a
    volumes:
      - ./Envoy/envoy-local.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/ssl/:/etc/ssl

  quartz_web_task_service:
    image: marekbf3/quartz-web-task-service
    ports:
      - '5001:80'
    environment: 
      - "ClientKey=testk"
      - "ManagmentKey=testm"

  mongodb:
    image: ${DOCKER_REGISTRY-}auctionhouse-mongodb-standalone
    ports:
      - '27017:27017'
    build:
      context: ./MongoDb/standalone
      dockerfile: Dockerfile-mongo-standalone-replicaset

  sql_server:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Qwerty1234
      - MSSQL_AGENT_ENABLED=True
    ports:
      - '1433:1433'
    image: marekbf3/auctionhouse-sqlserver


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  seq:
    image: datalust/seq
    environment:
        - ACCEPT_EULA=y
    ports:
        - '8011:80'
        - '5341:5341'

  redis:
    image: redis
    ports:
      - '6379:6379'