trigger:
 branches:
  include:
    - master
 paths:
   include:
     - front

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'front'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'front'
    customCommand: 'run build -- -c=production'
- task: Docker@2
  displayName: 'Build and push docker image'
  inputs:
    containerRegistry: 'VPSDockerRegistry'
    repository: 'pekalam/auctionhouse-front'
    command: 'buildAndPush'
    Dockerfile: 'front/Dockerfile.hosting'
    tags: 'latest'
- task: SSH@0
  displayName: 'Deploy on target machine'
  inputs:
    sshEndpoint: 'OVH_vps'
    runOptions: 'commands'
    commands: 'docker pull pekalam.me:5000/pekalam/auctionhouse-front:latest && docker service update auctionhouse_front --image pekalam.me:5000/pekalam/auctionhouse-front:latest'
    failOnStdErr: false
    readyTimeout: '20000'
