version: '3.4'

services:
  db-node1:
    hostname: db-node1
    container_name: db-node1
    image: mongo
#    tmpfs: /data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "n1", "--shardsvr" ]
networks:
    default:
        external:
            name: auctionhouse_network
