version: '3.4'

services:
  db-config1:
    command: "--configsvr --replSet configRS --bind_ip_all --keyFile=/data/mongocluster-keyfile"
    secrets:
      - mongocluster-keyfile 
  mongodb:
    command: ["--wait-for", "db-config1:32112", "db-node1:32112", "db-node2:32112", "db-node3:32112", "--configdb", "configRS/db-config1:27019", "--bind_ip_all", "--keyFile=/data/mongocluster-keyfile"]
    secrets:
      - mongocluster-keyfile 
  db-node1:
    command: [ "--bind_ip_all", "--replSet", "n1", "--shardsvr", "--keyFile=/data/mongocluster-keyfile" ]
    secrets:
      - mongocluster-keyfile 
  db-node2:
    command: [ "--bind_ip_all", "--replSet", "n2", "--shardsvr", "--keyFile=/data/mongocluster-keyfile" ]
    secrets:
      - mongocluster-keyfile 
  db-node3:
    command: [ "--bind_ip_all", "--replSet", "n3", "--shardsvr", "--keyFile=/data/mongocluster-keyfile" ]
    secrets:
      - mongocluster-keyfile 


secrets:
  mongocluster-keyfile:
    external: true