
stages:
- stage: Deploy
  displayName: 'Deploy Prod stage'
  jobs:
    - deployment: 'VPSDeployment'
      displayName: 'VPS Deployment'
      environment: vps-production
      strategy:
        runOnce:
          deploy:
            steps:
            - task: SSH@0
              displayName: 'Login to private registry'
              env:
                PEKALAM-REGISTRY-PASS: $(pekalam-registry-pass)
              inputs:
                sshEndpoint: 'OVH_vps'
                runOptions: 'commands'
                commands: '(docker login -u pekalam -p $(PEKALAM-REGISTRY-PASS) pekalam.me:5000 2>login_errorlog.txt || (cat login_errorlog.txt && exit 1)) && (test $(wc -l login_errorlog.txt | cut -d " " -f1) -gt 0 || rm login_errorlog.txt)'
                failOnStdErr: false
                readyTimeout: '20000'
            - task: SSH@0
              displayName: 'Deploy on target machine'
              inputs:
                sshEndpoint: 'OVH_vps'
                runOptions: 'commands'
                commands: 'docker pull pekalam.me:5000/pekalam/auctionhouse-front:latest && docker service update auctionhouse_front --with-registry-auth --image pekalam.me:5000/pekalam/auctionhouse-front:latest'
                readyTimeout: '20000'
