version: '3.4'

services:
  db-config1:
    hostname: db-config1
    container_name: db-config1
    build:
      context: config/config_1/
    tmpfs: /data/configdb
    command: "--configsvr --replSet configRS --bind_ip_all"
